### ISSUE TITLE
Javascript ES6

### ISSUE THREAD

**Issue by jacksonkr** [briandunnington/Roact#3]
What is the possibility of added javascript capabilities to this project? It would open a lot of doors. I'm thinking shared libraries between react or react-native libraries.

Is there any plan for this?

**Comment by jfrux** [comment]
I wish there was something like Babel that would generate Roku code somehow ... lol or something like ReactNative that generated Roku code.  I'd love to see an abstraction like this.  Would be sick.

**Comment by briandunnington** [comment]
The Roku runtime only supports writing apps in BrightScript. There have been a few attempts at creating a Javascript-to-BrightScript transpiler (see https://github.com/mattaylor/rokuJs and https://github.com/slheavner/js-to-bs for example - no affiliation) but nothing official.

Even ReactNative uses the Javascript runtime behind the scenes, and since Roku devices have no JS runtime, a transpiler that emits BrightScript is the only possibly technical solution.
